apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g2fdup55w-nodejs
  janus-idp.io/tekton: g2fdup55w-nodejs
  backstage.io/kubernetes-id: g2fdup55w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g2fdup55w-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
